### ISSUE TITLE
No creatures or objects visible on map after fresh install

### ISSUE THREAD

**Issue by vaughanb** [insthync/UnityMultiplayerARPG_UMA#11]
On a fresh install of the kit version 1.59b and addon version 1.16b_2019.4, no monsters, NPCs or objects appear on the map after loading into game. I tested this on single-player. Re-installed kit/UMA/addon several times with the same result. Loading from non-UMA init works as expected.

**Comment by insthync** [comment]
Try find and remove `LiteNetLibVisibleChecker` then add `GridVisibleChecker` component to prefab named `UMAPlayerCharacterEntity`

**Comment by vaughanb** [comment]
That appears to have fixed it. Thanks!
