### ISSUE TITLE
Not compatible with recent kit versions

### ISSUE THREAD

**Issue by vaughanb** [insthync/UnityMultiplayerARPG_UMA#12]
The add-on has not been compatible with the last few kit releases.

**Comment by insthync** [comment]
New release for `UMAExtension` just updated, But it's required CORE version `1.62`.

**Comment by vaughanb** [comment]
Looks like it's mostly working, but character deserialization is broken. Need to add namespace MultiplayerARPG to PlayerCharacterDataExtension_UMA.

**Comment by insthync** [comment]
Oh, thank you, I've fixed it.

**Comment by vaughanb** [comment]
No problem. Thank you!
