### ISSUE TITLE
Apk build wont function

### ISSUE THREAD

**Issue by narutohobo** [insthync/UnityMultiplayerARPG_UMA#13]
After building up a secne and testing it out on my Linux computer it loads and functions perfectly, but once a do a apk build of it and test it on my android, it goes to the map loading screen and loads half way, then the game exist off and quits the app, any solutions to this?

**Comment by insthync** [comment]
Is that you who show me the very big scene?

**Comment by narutohobo** [comment]
😅yes ,im trying to reach out everywere for help on this as much as possible

**Comment by insthync** [comment]
It's not relates to UMA, you should post it here https://github.com/suriyun-production/mmorpg-kit-docs/issues

But from your information your terrain (337500 width and length) and stars are too big
