### ISSUE TITLE
Deserialization not working on character select screen in MMO mode

### ISSUE THREAD

**Issue by vaughanb** [insthync/UnityMultiplayerARPG_UMA#14]
Although it is working in single-player, deserialization doesn't seem to be working on the character select screen in MMO. None of the customization options I select are appearing on my character in the character selection screen. It does appear to be working in game, however.

I tested this on a fresh install of MMORPG kit 1.62e and UMA addon version 1.16g with a newly created MySQL database.

**Comment by insthync** [comment]
Sorry for slowly responding, I just see this today, I've fixed it in `1.16h`
