### ISSUE TITLE
Wrong return type

### ISSUE THREAD

**Issue by nakedfighter3d** [insthync/UnityMultiplayerARPG_UMA#15]
I just made a fresh install of 1.62g, UMA 2.11.6, and this latest ARPG_UMA addon. It gives me a series of errors about the wrong return type. 
`Assets\UnityMultiplayerARPG_UMA-master\Scripts\MMO\UI\UIMmoCharacterListUMA.cs(14,59): error CS0407: 'UniTaskVoid UIMmoCharacterListUMA.OnRequestedCharacters(ResponseHandlerData, AckResponseCode, ResponseCharactersMessage)' has the wrong return type`

**Comment by insthync** [comment]
Fixed in 1.16h package
