### ISSUE TITLE
Says "user already logged in"

### ISSUE THREAD

**Issue by zerabic** [insthync/UnityMultiplayerARPG_UMA#16]
Issues after integrating UMA, i could log in and create once, but it now says "user already logged in"
Which i am not, i already exited the game.

**Comment by insthync** [comment]
Singleplay or MMO game?

**Comment by insthync** [comment]
Sorry, it's obviously is MMO games, right ? :P

Please zipping log files and post it here.

**Comment by zerabic** [comment]
Yeah, but feel free to close the issue, after updating the server a few times the issue dissapeared.
Thanks for this great MMOkit! **Rock on!**
