### ISSUE TITLE
Weapon specific animations don't work

### ISSUE THREAD

**Issue by vaughanb** [insthync/UnityMultiplayerARPG_UMA#2]
Most of the weapon-specific animations like Idle Clip, Move Clip, Jump, etc. do not work on the UMAPlayerCharacterEntity. Only the weapon-specific attack animations appear to function currently.

**Comment by insthync** [comment]
You're using CharacterModelUMA or AnimatorCharacterModelUMA ?

**Comment by vaughanb** [comment]
Looks like I'm using CharacterModelUMA. It was what the UMAPlayerCharacterEntity had when I installed the add-on.

**Comment by insthync** [comment]
Okay, if you're using `CharacterModelUMA` you have to set clips to `DefaultAnimatorData` as key for override by `AnimatorOverrideController` (https://docs.unity3d.com/Manual/AnimatorOverrideController.html)

![Screenshot_202](https://user-images.githubusercontent.com/2697550/69866379-7a288a80-12d6-11ea-8143-881281912e5f.png)

** Clips are the same clips in animator controller states **

![Screenshot_203](https://user-images.githubusercontent.com/2697550/69866459-b360fa80-12d6-11ea-8b68-cd14000b38e8.png)

**Comment by vaughanb** [comment]
After doing this, the animations now appear to be working. Thank you. I will close the issue.
