### ISSUE TITLE
Adding Hair To Character Creator

### ISSUE THREAD

**Issue by dejoshuab** [insthync/UnityMultiplayerARPG_UMA#23]
Hi, I just brought uma hair pack vol 2 and I was wondering how to add the hair to uma character creation dropdown?

**Comment by insthync** [comment]
Try add recipe here
![Screenshot_970](https://user-images.githubusercontent.com/2697550/155533285-63a7e7be-9f92-45ad-9f6a-3b5f0be0020b.png)

**Comment by dejoshuab** [comment]
Thank you that worked
