### ISSUE TITLE
Current issues which break this addon

### ISSUE THREAD

**Issue by Fallen-Entertainment** [insthync/UnityMultiplayerARPG_UMA#24]
another user asked for help so i loaded up the addon and set out to debug it. The first issue was a simple one it was the layer name change. I fixed that and then moved on to the fina1 3 errors left. 

![image](https://user-images.githubusercontent.com/71889605/156680968-cb82ffe7-8fa5-4af0-8dfb-50abecf54bde.png)

rightHandEquipmentEntity and leftHandEquipmentEntity are broken I tried messing with it but didnt come up with a fix.
Not sure what to do there but those make up the final 3 errors.

**Comment by moepi2k** [comment]
Just change to cacheRightHandEquipmentEntity

**Comment by Fallen-Entertainment** [comment]
It seems that its the instructions that are at fault. People are reading them and downloading the addon from the wrong place. Thanks to Neomis's help between us we figured out what was going on. Maybe update the instructions to avoid this issue in the future. I know your busy though and in the mean time at least i can inform people with issues of what to do.

**Comment by Rupturegames** [comment]
What was the solution you found?

**Comment by insthync** [comment]
Did you try downloading directly from the repo ?, I mean to not download from Release section, because I can forget to upload new release sometime.

**Comment by moepi2k** [comment]
yea that was the problem, he used an old link from discord. 

you can close :)
