### ISSUE TITLE
Required core overrides in 1.76d2?

### ISSUE THREAD

**Issue by johnmoney** [insthync/UnityMultiplayerARPG_UMA#29]
Thanks for the PlayableUMA! It's much appreciated.

Installed tonight on 1.76d2 and ran into the a few errors that needed fixing to get it to compile.

- in PlayableCharacterModel, changed Start() from private to protected virtual
- in AnimatorCharacterModel, changed ConvertToPlayableCharacterModelImplement() from public to public virtual
- in AnimatorCharacterModelUMA, commented out ConvertToPlayableCharacterModelGeneric in ConvertToPlayableCharacterModelImplement (could not find that method in my codebase)

Not sure if these are required or a bad install on my part?

**Comment by insthync** [comment]
I've written some note about it here: https://github.com/insthync/UnityMultiplayerARPG_UMA/releases/tag/1.18

**Comment by johnmoney** [comment]
Aha! Yup, I should have checked. Just pulled master.
