### ISSUE TITLE
Protection levels / AnimatorCharacterModel does not take parameter on ConvertToPlayableCharacterModelImplement()

### ISSUE THREAD

**Issue by ghost** [insthync/UnityMultiplayerARPG_UMA#30]
Missing virtuals in PlayableCharacterModelUma,  and AnimatorCharacterModel does not take a parameter in recent version.

**Comment by insthync** [comment]
Did you try changes codes as described here : https://github.com/insthync/UnityMultiplayerARPG_UMA/releases/tag/1.18
