### ISSUE TITLE
After the 1.77d update issue with the PlayableCharacterModelUMA.cs

### ISSUE THREAD

**Issue by runningbird** [insthync/UnityMultiplayerARPG_UMA#31]
After the recent 1.77d udpate, there is an issue with the SetPlayingWeaponsTypID.
Looked at the normal script and updated the UMA version to include the GetLeftHandShieldItem variable in the method call.

![image](https://user-images.githubusercontent.com/808741/194721793-73b41ece-63d5-4c7b-98cc-6df84eb7ce25.png)

change line 73 from Behaviour.SetPlayingWeaponTypeId(rightWeaponItem, leftWeaponItem);
to Behaviour.SetPlayingWeaponTypeId(rightWeaponItem, leftWeaponItem, equipWeapons.GetLeftHandShieldItem());

**Comment by insthync** [comment]
You can create a pull request for this
