### ISSUE TITLE
Error on latest Kit Version

### ISSUE THREAD

**Issue by AsheshPlays** [insthync/UnityMultiplayerARPG_UMA#33]
1st Error:
Assets\UMAExtension\Scripts\AnimatorCharacterModelUMA.cs(53,30): error CS0115: 'AnimatorCharacterModelUMA.SetEquipWeapons(EquipWeapons)': no suitable method found to override

2nd Error:
Assets\UMAExtension\Scripts\PlayableCharacterModelUMA.cs(60,30): error CS0115: 'PlayableCharacterModelUMA.SetEquipWeapons(EquipWeapons)': no suitable method found to override

Edit: I just realized its for 1.80 only. Sorry.

**Comment by insthync** [comment]
If you having problem then just tell me, then I will fix it almost immediately, don't ask about update date, it is annoying. 

This one is easy to fix, just changes some code, maybe just 2 lines of code. But after I read this. 

But now, I just not in mood to fix it, why I did something open source and then people just think that they can order me to do anything for free, thing is my feeling now.

**Comment by AsheshPlays** [comment]
@insthync 

Sorry sir. I was not aware of what to ask and what not to ask. I just simply asked and sorry for it. I am sorry if you felt that way when i asked but I am not ordering you anything. I simply stated that there is an error and I lately realized it was for 1.80 only.

Once again, i apologize.

**Comment by insthync** [comment]
You can tell me when you have problem, just delete this part "When will this be updated ?" that will be okay.
