### ISSUE TITLE
MMO Server Build after installing this package crashes

### ISSUE THREAD

**Issue by Vygar** [insthync/UnityMultiplayerARPG_UMA#37]
It seems that after installing this package with the latest version of the MMOkit causes the build to crash (and subsequently delete itself).  The only change I made was instlal this UMA package and use the related ini scenes and then follow the normal installation process for a MySQL Backend.  The only error I am able to go by from the logs is the following from the Guilwar Allocation file:

ERROR No Tag [2024-03-09 01:18:18] - NullReferenceException: Object reference not set to an instance of an object
MultiplayerARPG.MMO.MapNetworkManager.PreSpawnEntities () (at <a2363e1c06e3496dbb6b7a89ca54b105>:0)
Cysharp.Threading.Tasks.UniTask+ExceptionResultSource.GetResult (System.Int16 token) (at <e102cf80ab434eea8d96129965b25746>:0)
MultiplayerARPG.BaseGameNetworkManager.SpawnEntities () (at <a2363e1c06e3496dbb6b7a89ca54b105>:0)
UnityEngine.Debug:LogException(Exception)
Cysharp.Threading.Tasks.UniTaskScheduler:PublishUnobservedTaskException(Exception)
MultiplayerARPG.<SpawnEntities>d__238:MoveNext()
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskVoid`1:Run()
Cysharp.Threading.Tasks.Internal.ContinuationQueue:RunCore()
Cysharp.Threading.Tasks.Internal.ContinuationQueue:Run()

**Comment by insthync** [comment]
I will check it

**Comment by insthync** [comment]
Which UMA version ?

**Comment by Vygar** [comment]
The current release of Uma2 on the asset store which I believe is Update 2.12

**Comment by insthync** [comment]
Can build servers as a development build, then run them then copy the log messages again?

**Comment by Vygar** [comment]
Map Spawn .info

 INFO RestDatabaseClient [2024-03-09 01:18:14] - Reading config file from ./Config/serverConfig.json
 INFO RestDatabaseClient [2024-03-09 01:18:14] - Found config file
 INFO DatabaseUserLoginSetup [2024-03-09 01:18:15] - `UserLoginManager` not setup yet, Get it in children to setup...
 INFO DatabaseUserLoginSetup [2024-03-09 01:18:15] - `UserLoginManager` not setup yet, Use default one...
 INFO DatabaseUserLoginSetup [2024-03-09 01:18:15] - `UserLoginManager` not setup yet, Get it in children to setup...
 INFO DatabaseUserLoginSetup [2024-03-09 01:18:15] - `UserLoginManager` not setup yet, Use default one...
 INFO No Tag [2024-03-09 01:18:15] - [DevExt] GameInstance - LoadedGameData
 INFO GameInstance [2024-03-09 01:18:15] - [IAP_INIT]: Initialized without purchasing
 INFO DatabaseNetworkManager(DatabaseNetworkManager) [2024-03-09 01:18:15] - OnStartServer
 INFO MySQLDatabase [2024-03-09 01:18:15] - Reading config file from ./Config/mySqlConfig.json
 INFO MySQLDatabase [2024-03-09 01:18:15] - Not found config file, creating a new one
 INFO CentralNetworkManager(CentralNetworkManager) [2024-03-09 01:18:15] - OnStartServer
 INFO ClusterClient:MapSpawnServer [2024-03-09 01:18:15] - Starting server
 INFO ClusterClient:MapSpawnServer [2024-03-09 01:18:15] - Connecting to Cluster Server: 127.0.0.1:6010
 INFO MapSpawnNetworkManager(MapSpawnNetworkManager) [2024-03-09 01:18:15] - OnStartServer
 INFO DatabaseNetworkManager(DatabaseNetworkManager) [2024-03-09 01:18:15] - OnStartClient
 INFO DatabaseNetworkManager(DatabaseNetworkManager)->LiteNetLibClient [2024-03-09 01:18:15] - OnClientConnected
 INFO ClusterClient:MapSpawnServer [2024-03-09 01:18:15] - OnClientConnected
 INFO ClusterClient:MapSpawnServer [2024-03-09 01:18:15] - Connected to Cluster Server
 INFO ClusterClient:MapSpawnServer [2024-03-09 01:18:15] - App Register is requesting
 INFO DatabaseNetworkManager(DatabaseNetworkManager)->LiteNetLibServer [2024-03-09 01:18:15] - OnPeerConnected peer.ConnectionId: 0
 INFO ClusterServer [2024-03-09 01:18:15] - OnPeerConnected peer.ConnectionId: 0
 INFO ClusterServer [2024-03-09 01:18:15] - Register Map Spawn Server: [0]
 INFO ClusterClient:MapSpawnServer [2024-03-09 01:18:15] - App Registered successfully
 INFO MapSpawnNetworkManager(MapSpawnNetworkManager) [2024-03-09 01:18:15] - Starting process from: D:\Games\MMOD\MMOKitUma.exe
 INFO MapSpawnNetworkManager(MapSpawnNetworkManager) [2024-03-09 01:18:15] - Starting process with args: -batchmode -nographics  -channelId 1  -mapName Map001 -centralAddress 127.0.0.1 -centralPort 6010 -machineAddress 192.168.1.64 -mapPort 8000 -startMapServer
 INFO MapSpawnNetworkManager(MapSpawnNetworkManager) [2024-03-09 01:18:15] - Process started. Id: 7872
 INFO MapSpawnNetworkManager(MapSpawnNetworkManager) [2024-03-09 01:18:16] - Starting process from: D:\Games\MMOD\MMOKitUma.exe
 INFO MapSpawnNetworkManager(MapSpawnNetworkManager) [2024-03-09 01:18:16] - Starting process with args: -batchmode -nographics  -channelId 2  -mapName Map001 -centralAddress 127.0.0.1 -centralPort 6010 -machineAddress 192.168.1.64 -mapPort 8001 -startMapServer
 INFO MapSpawnNetworkManager(MapSpawnNetworkManager) [2024-03-09 01:18:16] - Process started. Id: 52740
 INFO MapSpawnNetworkManager(MapSpawnNetworkManager) [2024-03-09 01:18:16] - Starting process from: D:\Games\MMOD\MMOKitUma.exe
 INFO MapSpawnNetworkManager(MapSpawnNetworkManager) [2024-03-09 01:18:16] - Starting process with args: -batchmode -nographics  -channelId 1  -mapName Map002 -centralAddress 127.0.0.1 -centralPort 6010 -machineAddress 192.168.1.64 -mapPort 8002 -startMapServer
 INFO MapSpawnNetworkManager(MapSpawnNetworkManager) [2024-03-09 01:18:16] - Process started. Id: 27264
 INFO MapSpawnNetworkManager(MapSpawnNetworkManager) [2024-03-09 01:18:16] - Starting process from: D:\Games\MMOD\MMOKitUma.exe
 INFO MapSpawnNetworkManager(MapSpawnNetworkManager) [2024-03-09 01:18:16] - Starting process with args: -batchmode -nographics  -channelId 2  -mapName Map002 -centralAddress 127.0.0.1 -centralPort 6010 -machineAddress 192.168.1.64 -mapPort 8003 -startMapServer
 INFO MapSpawnNetworkManager(MapSpawnNetworkManager) [2024-03-09 01:18:16] - Process started. Id: 9048
 INFO MapSpawnNetworkManager(MapSpawnNetworkManager) [2024-03-09 01:18:16] - Starting process from: D:\Games\MMOD\MMOKitUma.exe
 INFO MapSpawnNetworkManager(MapSpawnNetworkManager) [2024-03-09 01:18:16] - Starting process with args: -batchmode -nographics  -channelId 1  -mapName Map_GuildWar -centralAddress 127.0.0.1 -centralPort 6010 -machineAddress 192.168.1.64 -mapPort 8004 -startMapServer
 INFO MapSpawnNetworkManager(MapSpawnNetworkManager) [2024-03-09 01:18:16] - Process started. Id: 14528
 INFO MapSpawnNetworkManager(MapSpawnNetworkManager) [2024-03-09 01:18:16] - Starting process from: D:\Games\MMOD\MMOKitUma.exe
 INFO MapSpawnNetworkManager(MapSpawnNetworkManager) [2024-03-09 01:18:16] - Starting process with args: -batchmode -nographics  -channelId 2  -mapName Map_GuildWar -centralAddress 127.0.0.1 -centralPort 6010 -machineAddress 192.168.1.64 -mapPort 8005 -startMapServer
 INFO MapSpawnNetworkManager(MapSpawnNetworkManager) [2024-03-09 01:18:16] - Process started. Id: 32292
 INFO DatabaseNetworkManager(DatabaseNetworkManager)->LiteNetLibServer [2024-03-09 01:18:18] - OnPeerConnected peer.ConnectionId: 1
 INFO DatabaseNetworkManager(DatabaseNetworkManager)->LiteNetLibServer [2024-03-09 01:18:18] - OnPeerConnected peer.ConnectionId: 2
 INFO DatabaseNetworkManager(DatabaseNetworkManager)->LiteNetLibServer [2024-03-09 01:18:18] - OnPeerConnected peer.ConnectionId: 3
 INFO DatabaseNetworkManager(DatabaseNetworkManager)->LiteNetLibServer [2024-03-09 01:18:18] - OnPeerConnected peer.ConnectionId: 4
 INFO DatabaseNetworkManager(DatabaseNetworkManager)->LiteNetLibServer [2024-03-09 01:18:18] - OnPeerConnected peer.ConnectionId: 5
 INFO DatabaseNetworkManager(DatabaseNetworkManager)->LiteNetLibServer [2024-03-09 01:18:18] - OnPeerConnected peer.ConnectionId: 6
 INFO ClusterServer [2024-03-09 01:18:19] - OnPeerConnected peer.ConnectionId: 1
 INFO ClusterServer [2024-03-09 01:18:19] - Register Map Server: [1] [1_Map002]
 INFO ClusterServer [2024-03-09 01:18:20] - OnPeerConnected peer.ConnectionId: 2
 INFO ClusterServer [2024-03-09 01:18:20] - Register Map Server: [2] [2_Map002]
 INFO ClusterServer [2024-03-09 01:18:20] - OnPeerConnected peer.ConnectionId: 3
 INFO ClusterServer [2024-03-09 01:18:20] - OnPeerConnected peer.ConnectionId: 4
 INFO ClusterServer [2024-03-09 01:18:20] - Register Map Server: [3] [1_Map001]
 INFO ClusterServer [2024-03-09 01:18:20] - Register Map Server: [4] [2_Map001]
 INFO No Tag [2024-03-10 15:23:37] -  INFO RestDatabaseClient [2024-03-10 15:23:37] - Reading config file from ./Config/serverConfig.json
 INFO RestDatabaseClient [2024-03-10 15:23:37] - Reading config file from ./Config/serverConfig.json
 INFO No Tag [2024-03-10 15:23:37] -  INFO RestDatabaseClient [2024-03-10 15:23:37] - Found config file
 INFO RestDatabaseClient [2024-03-10 15:23:37] - Found config file
 INFO No Tag [2024-03-10 15:23:37] -  INFO DatabaseUserLoginSetup [2024-03-10 15:23:37] - `UserLoginManager` not setup yet, Get it in children to setup...
 INFO DatabaseUserLoginSetup [2024-03-10 15:23:37] - `UserLoginManager` not setup yet, Get it in children to setup...
 INFO No Tag [2024-03-10 15:23:37] -  INFO DatabaseUserLoginSetup [2024-03-10 15:23:37] - `UserLoginManager` not setup yet, Use default one...
 INFO DatabaseUserLoginSetup [2024-03-10 15:23:37] - `UserLoginManager` not setup yet, Use default one...
 INFO No Tag [2024-03-10 15:23:37] -  INFO DatabaseUserLoginSetup [2024-03-10 15:23:37] - `UserLoginManager` not setup yet, Get it in children to setup...
 INFO DatabaseUserLoginSetup [2024-03-10 15:23:37] - `UserLoginManager` not setup yet, Get it in children to setup...
 INFO No Tag [2024-03-10 15:23:37] -  INFO DatabaseUserLoginSetup [2024-03-10 15:23:37] - `UserLoginManager` not setup yet, Use default one...
 INFO DatabaseUserLoginSetup [2024-03-10 15:23:37] - `UserLoginManager` not setup yet, Use default one...
 INFO No Tag [2024-03-10 15:23:37] - [DevExt] GameInstance - LoadedGameData
 INFO No Tag [2024-03-10 15:23:37] -  INFO GameInstance [2024-03-10 15:23:37] - [IAP_INIT]: Initialized without purchasing
 INFO GameInstance [2024-03-10 15:23:37] - [IAP_INIT]: Initialized without purchasing
 INFO No Tag [2024-03-10 15:23:37] -  INFO DatabaseNetworkManager(DatabaseNetworkManager) [2024-03-10 15:23:37] - OnStartServer
 INFO DatabaseNetworkManager(DatabaseNetworkManager) [2024-03-10 15:23:37] - OnStartServer
 INFO No Tag [2024-03-10 15:23:37] -  INFO MySQLDatabase [2024-03-10 15:23:37] - Reading config file from ./Config/mySqlConfig.json
 INFO MySQLDatabase [2024-03-10 15:23:37] - Reading config file from ./Config/mySqlConfig.json
 INFO No Tag [2024-03-10 15:23:37] -  INFO MySQLDatabase [2024-03-10 15:23:37] - Found config file
 INFO MySQLDatabase [2024-03-10 15:23:37] - Found config file
 INFO No Tag [2024-03-10 15:23:37] -  INFO CentralNetworkManager(CentralNetworkManager) [2024-03-10 15:23:37] - OnStartServer
 INFO CentralNetworkManager(CentralNetworkManager) [2024-03-10 15:23:37] - OnStartServer
 INFO No Tag [2024-03-10 15:23:37] -  INFO ClusterClient:MapSpawnServer [2024-03-10 15:23:37] - Starting server
 INFO ClusterClient:MapSpawnServer [2024-03-10 15:23:37] - Starting server
 INFO No Tag [2024-03-10 15:23:37] -  INFO ClusterClient:MapSpawnServer [2024-03-10 15:23:37] - Connecting to Cluster Server: 127.0.0.1:6010
 INFO ClusterClient:MapSpawnServer [2024-03-10 15:23:37] - Connecting to Cluster Server: 127.0.0.1:6010
 INFO No Tag [2024-03-10 15:23:37] -  INFO MapSpawnNetworkManager(MapSpawnNetworkManager) [2024-03-10 15:23:37] - OnStartServer
 INFO MapSpawnNetworkManager(MapSpawnNetworkManager) [2024-03-10 15:23:37] - OnStartServer
 INFO No Tag [2024-03-10 15:23:37] -  INFO DatabaseNetworkManager(DatabaseNetworkManager) [2024-03-10 15:23:37] - OnStartClient
 INFO DatabaseNetworkManager(DatabaseNetworkManager) [2024-03-10 15:23:37] - OnStartClient
 INFO No Tag [2024-03-10 15:23:37] -  INFO DatabaseNetworkManager(DatabaseNetworkManager)->LiteNetLibClient [2024-03-10 15:23:37] - OnClientConnected
 INFO DatabaseNetworkManager(DatabaseNetworkManager)->LiteNetLibClient [2024-03-10 15:23:37] - OnClientConnected
 INFO No Tag [2024-03-10 15:23:37] -  INFO ClusterClient:MapSpawnServer [2024-03-10 15:23:37] - OnClientConnected
 INFO ClusterClient:MapSpawnServer [2024-03-10 15:23:37] - OnClientConnected
 INFO No Tag [2024-03-10 15:23:37] -  INFO ClusterClient:MapSpawnServer [2024-03-10 15:23:37] - Connected to Cluster Server
 INFO ClusterClient:MapSpawnServer [2024-03-10 15:23:37] - Connected to Cluster Server
 INFO No Tag [2024-03-10 15:23:37] -  INFO ClusterClient:MapSpawnServer [2024-03-10 15:23:37] - App Register is requesting
 INFO ClusterClient:MapSpawnServer [2024-03-10 15:23:37] - App Register is requesting
 INFO No Tag [2024-03-10 15:23:37] -  INFO DatabaseNetworkManager(DatabaseNetworkManager)->LiteNetLibServer [2024-03-10 15:23:37] - OnPeerConnected peer.ConnectionId: 0
 INFO DatabaseNetworkManager(DatabaseNetworkManager)->LiteNetLibServer [2024-03-10 15:23:37] - OnPeerConnected peer.ConnectionId: 0
 INFO No Tag [2024-03-10 15:23:37] -  INFO ClusterServer [2024-03-10 15:23:37] - OnPeerConnected peer.ConnectionId: 0
 INFO ClusterServer [2024-03-10 15:23:37] - OnPeerConnected peer.ConnectionId: 0
 INFO No Tag [2024-03-10 15:23:37] -  INFO ClusterServer [2024-03-10 15:23:37] - Register Map Spawn Server: [0]
 INFO ClusterServer [2024-03-10 15:23:37] - Register Map Spawn Server: [0]
 INFO No Tag [2024-03-10 15:23:37] -  INFO ClusterClient:MapSpawnServer [2024-03-10 15:23:37] - App Registered successfully
 INFO ClusterClient:MapSpawnServer [2024-03-10 15:23:37] - App Registered successfully
 INFO No Tag [2024-03-10 15:23:38] -  INFO MapSpawnNetworkManager(MapSpawnNetworkManager) [2024-03-10 15:23:38] - Starting process from: D:\Games\MMOD\MMOKitUma.exe
 INFO MapSpawnNetworkManager(MapSpawnNetworkManager) [2024-03-10 15:23:38] - Starting process from: D:\Games\MMOD\MMOKitUma.exe
 INFO No Tag [2024-03-10 15:23:38] -  INFO MapSpawnNetworkManager(MapSpawnNetworkManager) [2024-03-10 15:23:38] - Starting process with args: -batchmode -nographics  -channelId 1  -mapName Map001 -centralAddress 127.0.0.1 -centralPort 6010 -machineAddress 192.168.1.64 -mapPort 8000 -startMapServer
 INFO MapSpawnNetworkManager(MapSpawnNetworkManager) [2024-03-10 15:23:38] - Starting process with args: -batchmode -nographics  -channelId 1  -mapName Map001 -centralAddress 127.0.0.1 -centralPort 6010 -machineAddress 192.168.1.64 -mapPort 8000 -startMapServer
 INFO No Tag [2024-03-10 15:23:38] -  INFO MapSpawnNetworkManager(MapSpawnNetworkManager) [2024-03-10 15:23:38] - Process started. Id: 34960
 INFO MapSpawnNetworkManager(MapSpawnNetworkManager) [2024-03-10 15:23:38] - Process started. Id: 34960
 INFO No Tag [2024-03-10 15:23:38] -  INFO MapSpawnNetworkManager(MapSpawnNetworkManager) [2024-03-10 15:23:38] - Starting process from: D:\Games\MMOD\MMOKitUma.exe
 INFO MapSpawnNetworkManager(MapSpawnNetworkManager) [2024-03-10 15:23:38] - Starting process from: D:\Games\MMOD\MMOKitUma.exe
 INFO No Tag [2024-03-10 15:23:38] -  INFO MapSpawnNetworkManager(MapSpawnNetworkManager) [2024-03-10 15:23:38] - Starting process with args: -batchmode -nographics  -channelId 2  -mapName Map001 -centralAddress 127.0.0.1 -centralPort 6010 -machineAddress 192.168.1.64 -mapPort 8001 -startMapServer
 INFO MapSpawnNetworkManager(MapSpawnNetworkManager) [2024-03-10 15:23:38] - Starting process with args: -batchmode -nographics  -channelId 2  -mapName Map001 -centralAddress 127.0.0.1 -centralPort 6010 -machineAddress 192.168.1.64 -mapPort 8001 -startMapServer
 INFO No Tag [2024-03-10 15:23:38] -  INFO MapSpawnNetworkManager(MapSpawnNetworkManager) [2024-03-10 15:23:38] - Process started. Id: 35384
 INFO MapSpawnNetworkManager(MapSpawnNetworkManager) [2024-03-10 15:23:38] - Process started. Id: 35384
 INFO No Tag [2024-03-10 15:23:38] -  INFO MapSpawnNetworkManager(MapSpawnNetworkManager) [2024-03-10 15:23:38] - Starting process from: D:\Games\MMOD\MMOKitUma.exe
 INFO MapSpawnNetworkManager(MapSpawnNetworkManager) [2024-03-10 15:23:38] - Starting process from: D:\Games\MMOD\MMOKitUma.exe
 INFO No Tag [2024-03-10 15:23:38] -  INFO MapSpawnNetworkManager(MapSpawnNetworkManager) [2024-03-10 15:23:38] - Starting process with args: -batchmode -nographics  -channelId 1  -mapName Map002 -centralAddress 127.0.0.1 -centralPort 6010 -machineAddress 192.168.1.64 -mapPort 8002 -startMapServer
 INFO MapSpawnNetworkManager(MapSpawnNetworkManager) [2024-03-10 15:23:38] - Starting process with args: -batchmode -nographics  -channelId 1  -mapName Map002 -centralAddress 127.0.0.1 -centralPort 6010 -machineAddress 192.168.1.64 -mapPort 8002 -startMapServer
 INFO No Tag [2024-03-10 15:23:38] -  INFO MapSpawnNetworkManager(MapSpawnNetworkManager) [2024-03-10 15:23:38] - Process started. Id: 35248
 INFO MapSpawnNetworkManager(MapSpawnNetworkManager) [2024-03-10 15:23:38] - Process started. Id: 35248
 INFO No Tag [2024-03-10 15:23:38] -  INFO MapSpawnNetworkManager(MapSpawnNetworkManager) [2024-03-10 15:23:38] - Starting process from: D:\Games\MMOD\MMOKitUma.exe
 INFO MapSpawnNetworkManager(MapSpawnNetworkManager) [2024-03-10 15:23:38] - Starting process from: D:\Games\MMOD\MMOKitUma.exe
 INFO No Tag [2024-03-10 15:23:38] -  INFO MapSpawnNetworkManager(MapSpawnNetworkManager) [2024-03-10 15:23:38] - Starting process with args: -batchmode -nographics  -channelId 2  -mapName Map002 -centralAddress 127.0.0.1 -centralPort 6010 -machineAddress 192.168.1.64 -mapPort 8003 -startMapServer
 INFO MapSpawnNetworkManager(MapSpawnNetworkManager) [2024-03-10 15:23:38] - Starting process with args: -batchmode -nographics  -channelId 2  -mapName Map002 -centralAddress 127.0.0.1 -centralPort 6010 -machineAddress 192.168.1.64 -mapPort 8003 -startMapServer
 INFO No Tag [2024-03-10 15:23:38] -  INFO MapSpawnNetworkManager(MapSpawnNetworkManager) [2024-03-10 15:23:38] - Process started. Id: 23760
 INFO MapSpawnNetworkManager(MapSpawnNetworkManager) [2024-03-10 15:23:38] - Process started. Id: 23760
 INFO No Tag [2024-03-10 15:23:43] -  INFO DatabaseNetworkManager(DatabaseNetworkManager)->LiteNetLibServer [2024-03-10 15:23:43] - OnPeerConnected peer.ConnectionId: 1
 INFO DatabaseNetworkManager(DatabaseNetworkManager)->LiteNetLibServer [2024-03-10 15:23:43] - OnPeerConnected peer.ConnectionId: 1
 INFO No Tag [2024-03-10 15:23:44] -  INFO DatabaseNetworkManager(DatabaseNetworkManager)->LiteNetLibServer [2024-03-10 15:23:44] - OnPeerConnected peer.ConnectionId: 2
 INFO DatabaseNetworkManager(DatabaseNetworkManager)->LiteNetLibServer [2024-03-10 15:23:44] - OnPeerConnected peer.ConnectionId: 2
 INFO No Tag [2024-03-10 15:23:44] -  INFO DatabaseNetworkManager(DatabaseNetworkManager)->LiteNetLibServer [2024-03-10 15:23:44] - OnPeerConnected peer.ConnectionId: 3
 INFO DatabaseNetworkManager(DatabaseNetworkManager)->LiteNetLibServer [2024-03-10 15:23:44] - OnPeerConnected peer.ConnectionId: 3
 INFO No Tag [2024-03-10 15:23:45] -  INFO ClusterServer [2024-03-10 15:23:45] - OnPeerConnected peer.ConnectionId: 1
 INFO ClusterServer [2024-03-10 15:23:45] - OnPeerConnected peer.ConnectionId: 1
 INFO No Tag [2024-03-10 15:23:45] -  INFO ClusterServer [2024-03-10 15:23:45] - Register Map Server: [1] [2_Map002]
 INFO ClusterServer [2024-03-10 15:23:45] - Register Map Server: [1] [2_Map002]
 INFO No Tag [2024-03-10 15:23:45] -  INFO ClusterServer [2024-03-10 15:23:45] - OnPeerConnected peer.ConnectionId: 2
 INFO ClusterServer [2024-03-10 15:23:45] - OnPeerConnected peer.ConnectionId: 2
 INFO No Tag [2024-03-10 15:23:45] -  INFO ClusterServer [2024-03-10 15:23:45] - Register Map Server: [2] [1_Map002]
 INFO ClusterServer [2024-03-10 15:23:45] - Register Map Server: [2] [1_Map002]

**Comment by Vygar** [comment]
Guild War Channel 1 error

**Comment by Vygar** [comment]
ERROR No Tag [2024-03-09 01:18:18] - NullReferenceException: Object reference not set to an instance of an object
MultiplayerARPG.MMO.MapNetworkManager.PreSpawnEntities () (at <a2363e1c06e3496dbb6b7a89ca54b105>:0)
Cysharp.Threading.Tasks.UniTask+ExceptionResultSource.GetResult (System.Int16 token) (at <e102cf80ab434eea8d96129965b25746>:0)
MultiplayerARPG.BaseGameNetworkManager.SpawnEntities () (at <a2363e1c06e3496dbb6b7a89ca54b105>:0)
UnityEngine.Debug:LogException(Exception)
Cysharp.Threading.Tasks.UniTaskScheduler:PublishUnobservedTaskException(Exception)
MultiplayerARPG.<SpawnEntities>d__238:MoveNext()
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskVoid`1:Run()
Cysharp.Threading.Tasks.Internal.ContinuationQueue:RunCore()
Cysharp.Threading.Tasks.Internal.ContinuationQueue:Run()

**Comment by Vygar** [comment]
Guild War Channel 2 error
ERROR No Tag [2024-03-09 01:18:18] - NullReferenceException: Object reference not set to an instance of an object
MultiplayerARPG.MMO.MapNetworkManager.PreSpawnEntities () (at <a2363e1c06e3496dbb6b7a89ca54b105>:0)
Cysharp.Threading.Tasks.UniTask+ExceptionResultSource.GetResult (System.Int16 token) (at <e102cf80ab434eea8d96129965b25746>:0)
MultiplayerARPG.BaseGameNetworkManager.SpawnEntities () (at <a2363e1c06e3496dbb6b7a89ca54b105>:0)
UnityEngine.Debug:LogException(Exception)
Cysharp.Threading.Tasks.UniTaskScheduler:PublishUnobservedTaskException(Exception)
MultiplayerARPG.<SpawnEntities>d__238:MoveNext()
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskVoid`1:Run()
Cysharp.Threading.Tasks.Internal.ContinuationQueue:RunCore()
Cysharp.Threading.Tasks.Internal.ContinuationQueue:Run()

**Comment by Vygar** [comment]
Log_map
ERROR No Tag [2024-03-10 15:23:45] - There is no texture data available to upload.

**Comment by Vygar** [comment]
I did do some debugging of the build and it looks as though the error occurs here in MapNetworkManager.PrespawnEntities
buildingsResp = await DbServiceClient.ReadBuildingsAsync(new ReadBuildingsReq()
                    {
                        ChannelId = ChannelId,
                        MapName = CurrentMapInfo.Id,
                    });

ChannelId and CurrentMapInfo are all null

**Comment by insthync** [comment]
Did you set the guild war scene in scenes in build?

Did you build it as development build as I told you? I expected that it will tells which line is error, because it is shows (at: 0) in your log messages

**Comment by nakedfighter3d** [comment]
> Which UMA version ?

It's unrelated to your issue but I just willing to let you know, that the assets store version UMA is outdated and not recommended for use. Updating the asset store is a hassle and devs didn't want to bother, but you always can find recent UMA here: https://github.com/umasteeringgroup/UMA/releases

UMA 2.13b is the recent stable release. The new release will  come soon in the next month or so

**Comment by Vygar** [comment]
Yes.  I built the project in Development Mode but when running the .exe it crashes and deletes itself.  After doing my own digging, the error occurs on (or around) line 501 of class MultiplayerARPG.MMO.MapNetworkManager; PreSpawnEntities() method.

**Comment by insthync** [comment]
When the error occured, it has no log files written in log folder?

**Comment by Vygar** [comment]
The only log file that has content are Log_Map(Map_GuildWar)-Channel(1)-Allocate(False)-Instance().err.log, Log_Map(Map_GuildWar)-Channel(2)-Allocate(False)-Instance().err.log

I can zip them up and put them on my dropbox if that helps

**Comment by Vygar** [comment]
https://www.dropbox.com/scl/fi/ipb9lwequ3ctt3gsecf5s/log.7z?rlkey=bjmhxr51fuqsr9tgs5qj8j1mb&dl=0

I zipped up the logs here

**Comment by insthync** [comment]
The logs are not from development build

**Comment by insthync** [comment]
Did you set the guild war scene in scenes in build? (I hope I won't have to ask you again)

**Comment by Vygar** [comment]
It is.  I have Development build checked in  the editor and I have attach debugger enabled as well.  I enabled developer level logging in the Server/client game objects and the resulting logs are the same.

**Comment by Vygar** [comment]
Here's from Player.log but there isn't much in here

Mono path[0] = 'D:/Games/MMOE/MMOKitUma_Data/Managed'
Mono config path = 'D:/Games/MMOE/MonoBleedingEdge/etc'
[Physics::Module] Initialized MultithreadedJobDispatcher with 11 workers.
Initialize engine version: 2022.3.20f1 (61c2feb0970d)
[Subsystems] Discovering subsystems at path D:/Games/MMOE/MMOKitUma_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1; jobified=0
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1070 Ti (ID=0x1b82)
    Vendor:   NVIDIA
    VRAM:     8073 MB
    Driver:   31.0.15.4633
Begin MonoManager ReloadAssembly
- Loaded All Assemblies, in  0.129 seconds
- Finished resetting the current domain, in  0.001 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.780600 ms
 INFO No Tag [2024-03-09 01:20:33] - ===== Logger Initialized =====
[DevExt] GameInstance - Awake
 INFO MMOServerInstance (MultiplayerARPG.MMO.MMOServerInstance) [2024-03-09 01:20:33] - Reading config file from ./Config/serverConfig.json
 INFO MMOServerInstance (MultiplayerARPG.MMO.MMOServerInstance) [2024-03-09 01:20:33] - Not found config file, creating a new one
[DevExt] GameInstance - LoadedGameData
Setting up 6 worker threads for Enlighten.

**Comment by insthync** [comment]
May I try it by using AnyDesk?

**Comment by Vygar** [comment]
Sure

**Comment by Vygar** [comment]
It might be easier to coordinate over discord.  Where should I send this invite?

**Comment by insthync** [comment]
No, I won't use Discord, send your AnyDesk info to my email: ittipon.bay@gmail.com, I will available in next 2 hours
