### ISSUE TITLE
Addressable UMA 2.10 and Unity 2019.3 issues 

### ISSUE THREAD

**Issue by nakedfighter3d** [insthync/UnityMultiplayerARPG_UMA#4]
Hey! I have issues with switching UMA race/dna. The bug is pretty random. Sometimes everything works fine, but sometimes when I 
1) create default Male character 
2) create default Female character 
3) switching between them in the **select character window** 
female loading with completely broken sizes/dna. Sometimes it works well in solo game mode, but bugged in MMO mode. Very random.

UMA has a major 2.10 update with the addressables support and many loading\performance improvements. Maybe it's somehow related. Also, it requires some changes in the pipeline and some integration fixes with MMO Kit as well. Here are my steps to set up a new project and reproduce the bug.

1. Setup new project with Unity 2019.3
2. Import MMORPG Kit
3. Import Addressables package
4. Copy latest UMA 2.10a3 from github
_--- start UMA setup part ---_
5. Add UMA_ADDRESSABLES to project settings/player settings
6. In the new **UMA / Global Library** select **Addressables/Generate Shared Group (fast)** 
7. In **Window/Asset Manager/Addressables** create new setup and  **Build Player Content**
_--- end UMA setup part ---_
8. Import UnityMultiplayerARPG_UMA_1.13_2018.2
9. in **UIUmaDnaSlider.cs** add to header **using UMA;**
10. Open 00init_UMA/00init_MMO_UMA/ and replace **UMA_DCS** with **UMA_GLIB**

![UMA_MMOKIT](https://user-images.githubusercontent.com/38335953/77290176-ff82e100-6cb1-11ea-8485-98381c68fdca.png)

**Comment by nakedfighter3d** [comment]
OK, I see that it's somehow connected with the error I got when switching from male race to female.

`KeyNotFoundException: The given key was not present in the dictionary.
System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <437ba245d8404784b9fbab9b439ac908>:0)
MultiplayerARPG.UIUmaDnaSlider.OnSliderValueChanged (System.Single value) (at Assets/UMAExtension/Scripts/UI/UIUmaDnaSlider.cs:55)
MultiplayerARPG.UIUmaDnaSlider.Setup (MultiplayerARPG.UICharacterCreateUMA ui, System.Byte slotIndex, UMA.DnaSetter dnaSetter) (at Assets/UMAExtension/Scripts/UI/UIUmaDnaSlider.cs:47)
MultiplayerARPG.UICharacterCreateUMA+<SetupDnas>d__40.MoveNext () (at Assets/UMAExtension/Scripts/UI/UICharacterCreateUMA.cs:158)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <d815b7efac424eeb8e053965cccb1f98>:0)`

After that, the character file we saved to the database has most of the DNA switched to zero.
i.e.
ArmLength = 0.5
ArmWidth = 0.5
BreastClevage = 0.5
...and after that all the DNA = 0

![DNA prblem](https://user-images.githubusercontent.com/38335953/77295996-3f02fa80-6cbd-11ea-989b-9fa5b47f98a0.png)

**Comment by nakedfighter3d** [comment]
UPD.2
it's definitely something related to the new UMA library approach.
With legacy UMA_DCS - everything is fine
With new UMA_GLIB - female character drops an error and fails to set/save DNAs

**Comment by nakedfighter3d** [comment]
**UPD: SOLUTION**
I reach out with UMA developers and they kindly provide me with this edit.

in **UIUmaDnaSlider.cs**, change the following:
`ui.UmaModel.CacheUmaAvatar.GetDNA()[dnaName].Set(value);`
to:
```
var DNA = ui.UmaModel.CacheUmaAvatar.GetDNA();
if (DNA.ContainsKey(dnaName))
{
   DNA[dnaName].Set(value);
}  
```

**Comment by insthync** [comment]
Oh, thank you, I will update the package later :)
