### ISSUE TITLE
 AnimatorCharacterModelUMA didn't load race/slots/equipment on start

### ISSUE THREAD

**Issue by nakedfighter3d** [insthync/UnityMultiplayerARPG_UMA#6]
During map change/creation AnimatorCharacterModelUMA load just default UMA naked man, no slots, equipment or race. If you unequip weapon or clothing _(and then equip back)_ - weapon and equipment appear properly. So it's not working only during the first character load on the map. 

Might be related to the fact that building the character is now delayed by at least 1 frame. _(this was the same in 2.9 if you used Asset Bundles)._ But adding Addressables, and then running the script to build them, basically turns everything into an asset bundle. So you are working on a different paradigm now.

**Comment by AnisimovArthur** [comment]
If you change CharacterModelUMA to AnimatorCharacterModelUMA in BasePlayerCharacterEntity_UMA.cs it will work

<img width="1081" alt="image" src="https://user-images.githubusercontent.com/39820747/78500257-09025380-775e-11ea-916c-6f1891f77cdd.png">

@insthync can you update it please? :)

**Comment by AnisimovArthur** [comment]
I made a request pool (https://github.com/insthync/UnityMultiplayerARPG_UMA/pull/7) as one of the solutions

**Comment by insthync** [comment]
Thank you :)
